CREATE OR REPLACE FUNCTION MYLIB.FORMAT_ZIP (
    ZIP5 CHAR(5),
    ZIP4 CHAR(4)
)
RETURNS CHAR(10)
LANGUAGE RPGLE
DETERMINISTIC
NO SQL
EXTERNAL NAME 'MYLIB/CALCSVCS(FORMATZIP)'
PARAMETER STYLE GENERAL;

CREATE OR REPLACE FUNCTION MYLIB.CALC_MONTHLY_PAYMENT (
    PRINCIPAL DECIMAL(15,2),
    RATE      DECIMAL(5,4),
    MONTHS    INTEGER
)
RETURNS DECIMAL(15,2)
LANGUAGE RPGLE
DETERMINISTIC
NO SQL
EXTERNAL NAME 'MYLIB/CALCSVCS(CALCULATEMONTHLYPAYMENT)'
PARAMETER STYLE GENERAL;

VALUES MYLIB.FORMAT_ZIP('75034', '1234');
-- '75034-1234'

VALUES MYLIB.CALC_MONTHLY_PAYMENT(10000.00, 0.0525, 36);
-- 300.83
